# Generated by Django 5.0.6 on 2024-07-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('label', models.TextField()),
                ('url_image', models.TextField()),
                ('url_npy', models.TextField()),
            ],
        ),
    ]
